// Generated by CoffeeScript 1.6.3
(function() {
  var fullscreenElement;

  fullscreenElement = function() {
    return document.fullscreenEnabled || document.mozFullScreenEnabled || document.webkitFullscreenEnabled;
  };

  ({
    hasFullscreen: function() {
      document.webkitIsFullScreen || document.mozFullScreen || document.requestFullscreen;
      return {
        toggleFullScreen: function() {
          var el;
          el = document.body;
          if (!this.isFullscreen()) {
            if (el.requestFullscreen) {
              return el.requestFullscreen();
            } else if (el.mozRequestFullScreen) {
              return el.mozRequestFullScreen();
            } else if (el.webkitRequestFullscreen) {
              return el.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT);
            }
          } else {
            if (document.cancelFullScreen) {
              return document.cancelFullScreen();
            } else if (document.mozCancelFullScreen) {
              return document.mozCancelFullScreen();
            } else if (document.webkitCancelFullScreen) {
              return document.webkitCancelFullScreen();
            }
          }
        }
      };
    }
  });

}).call(this);
