// Generated by CoffeeScript 1.6.3
(function() {
  var webglCapable,
    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  webglCapable = function() {
    var canvas, error, gl;
    canvas = document.createElement('canvas');
    try {
      gl = canvas.getContext("webgl");
    } catch (_error) {
      error = _error;
      gl = null;
    }
    if (gl === null) {
      try {
        gl = canvas.getContext("experimental-webgl");
      } catch (_error) {
        error = _error;
        gl = null;
      }
    }
    if (gl) {
      return true;
    } else if (__indexOf.call(window, "WebGLRenderingContext") >= 0) {
      return true;
    } else {
      return false;
    }
  };

  window.LL = window.LL || {};

  window.LL.webglCapable = webglCapable;

}).call(this);
