// Generated by CoffeeScript 1.6.3
(function() {
  var runDemo;

  runDemo = function(fn) {
    document.querySelector("#hud p").addEventListener('click', function(evt) {
      if (screenfull.enabled) {
        return screenfull.toggle();
      }
    });
    if (LL.webglCapable()) {
      return fn(document.getElementById("container"));
    } else {
      document.getElementById("container").style.display = "none";
      document.getElementById("hud").style.display = "none";
      return document.getElementById("webglfallback").style.display = "block";
    }
  };

  window.LL = window.LL || {};

  window.LL.runDemo = runDemo;

}).call(this);
