// Generated by CoffeeScript 1.6.3
(function() {
  var camera, cube, last_time, renderer, run, scene, start, start_stats, stats;

  renderer = null;

  scene = null;

  camera = null;

  cube = null;

  stats = null;

  start = function() {
    var container, geometry, light, map, mapUrl, material;
    container = document.getElementById("container");
    renderer = new THREE.WebGLRenderer();
    renderer.setSize(container.offsetWidth, container.offsetHeight);
    container.appendChild(renderer.domElement);
    scene = new THREE.Scene();
    camera = new THREE.PerspectiveCamera(45, container.offsetWidth / container.offsetHeight, 1, 4000);
    camera.position.set(0, 0, 4);
    light = new THREE.DirectionalLight(0xffffff, 1.5);
    light.position.set(0, 1, 1);
    scene.add(light);
    mapUrl = "img/molumen_small_funny_angry_monster.jpg";
    map = THREE.ImageUtils.loadTexture(mapUrl);
    material = new THREE.MeshPhongMaterial({
      map: map
    });
    geometry = new THREE.CubeGeometry(1, 1, 1);
    cube = new THREE.Mesh(geometry, material);
    cube.rotation.x = Math.PI / 5;
    cube.rotation.y = Math.PI / 5;
    scene.add(cube);
    start_stats();
    return run();
  };

  last_time = null;

  run = function(timestamp) {
    var progress;
    renderer.render(scene, camera);
    progress;
    if (timestamp === void 0) {
      timestamp = 0;
    }
    if (last_time === null) {
      last_time = timestamp;
    }
    progress = timestamp - last_time;
    cube.rotation.y -= (progress / 16.7) * 0.01;
    cube.rotation.x -= (progress / 16.7) * 0.01;
    cube.rotation.z -= (progress / 16.7) * 0.01;
    last_time = timestamp;
    stats.update();
    return requestAnimationFrame(run);
  };

  window.onload = function() {
    return start();
  };

  start_stats = function() {
    stats = new Stats();
    stats.domElement.style.position = 'absolute';
    stats.domElement.style.left = '0px';
    stats.domElement.style.top = '0px';
    return document.body.appendChild(stats.domElement);
  };

}).call(this);
